rootProject.name = 'my-minimal-playground'
include 'kafka:01-log-and-offset'
include 'kafka:02-partitions-and-groups'
include 'kafka:03-poll-timeout-and-commit'
include 'kafka:04-transactions-and-visibility'
include 'kafka:05-offsets-in-transaction'
include 'kafka:06-producer-fencing'
include 'kafka:07-replication-isr'
include 'kafka:08-idempotence-retries'
include 'kafka:09-retention-segments'
