package playground.jpa;

import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import jakarta.persistence.*;
import org.hibernate.Version;
import org.springframework.context.annotation.*;
import org.springframework.core.SpringVersion;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.orm.jpa.*;
import org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter;
import org.springframework.transaction.annotation.*;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import javax.sql.DataSource;
import java.sql.*;
import java.util.*;

public class JpaLab {
    static void check(boolean ok, String message) { if (!ok) throw new IllegalStateException(message); }
    static class RollbackProbe extends RuntimeException { }
    public static class Trace { final List<String> steps = new ArrayList<>(); }
    @Configuration
    @EnableTransactionManagement(proxyTargetClass = true)
    @EnableJpaRepositories(basePackageClasses = PostRepository.class)
    public static class Config {
        @Bean LocalContainerEntityManagerFactoryBean entityManagerFactory(DataSource ds) {
            var factory = new LocalContainerEntityManagerFactoryBean();
            factory.setDataSource(ds);
            factory.setPackagesToScan("playground.jpa");
            factory.setJpaVendorAdapter(new HibernateJpaVendorAdapter());
            factory.setJpaPropertyMap(Map.of("hibernate.hbm2ddl.auto", "none", "hibernate.show_sql", "false"));
            return factory;
        }
        @Bean JpaTransactionManager transactionManager(EntityManagerFactory factory) { return new JpaTransactionManager(factory); }
        @Bean JdbcTemplate jdbc(DataSource ds) { return new JdbcTemplate(ds); }
        @Bean Trace trace() { return new Trace(); }
        @Bean Db db(DataSource ds, JdbcTemplate jdbc) { return new Db(ds, jdbc); }
        @Bean Service service(PostRepository posts, Db db, Trace trace) { return new Service(posts, db, trace); }
    }
    public static class Db {
        final DataSource ds;
        final JdbcTemplate jdbc;
        Db(DataSource ds, JdbcTemplate jdbc) { this.ds = ds; this.jdbc = jdbc; }
        void init() {
            jdbc.execute("CREATE TABLE post_record (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL, slug text UNIQUE NOT NULL, title text NOT NULL)");
            jdbc.execute("CREATE TABLE outbox_record (id integer PRIMARY KEY, post_id bigint REFERENCES post_record(id) DEFERRABLE INITIALLY DEFERRED)");
        }
        void reset(boolean seed) {
            jdbc.execute("TRUNCATE outbox_record,post_record RESTART IDENTITY");
            if (seed) jdbc.update("INSERT INTO post_record(version,slug,title) VALUES (0,'first','old'),(0,'second','other')");
        }
        String same(String sql) { return jdbc.queryForObject(sql, String.class); }
        String observe(String sql) {
            // Direct DataSource access deliberately avoids the transaction-bound JdbcTemplate connection.
            try (var connection = ds.getConnection(); var statement = connection.createStatement()) {
                check(connection.getAutoCommit(), "Observer must use autocommit");
                check(connection.getTransactionIsolation() == Connection.TRANSACTION_READ_COMMITTED, "Observer isolation");
                statement.setQueryTimeout(5);
                try (var result = statement.executeQuery(sql)) { check(result.next(), "Missing observation"); return result.getString(1); }
            } catch (SQLException e) { throw new IllegalStateException(e); }
        }
        String row() { return observe("SELECT title || ':' || version FROM post_record WHERE id=1"); }
    }
    public static class Service {
        final PostRepository posts;
        final Db db;
        final Trace trace;
        @PersistenceContext EntityManager em;
        Service(PostRepository posts, Db db, Trace trace) { this.posts = posts; this.db = db; this.trace = trace; }
        void note(String value) { trace.steps.add(value); }
        @Transactional public void identityRollback() {
            Post post = posts.save(new Post("new", "new"));
            check(post.id() != null, "IDENTITY must be assigned");
            String sql = "SELECT count(*) FROM post_record";
            check(db.same(sql).equals("1") && db.observe(sql).equals("0"), "Identity visibility");
            note("save:same=1,observer=0,idAssigned=true");
            em.flush();
            check(db.observe(sql).equals("0"), "Flush must not publish");
            note("flush:observer=0");
            throw new RollbackProbe();
        }
        @Transactional public void flushThenCommit() {
            posts.saveAndFlush(new Post("new", "new"));
            check(db.same("SELECT count(*) FROM post_record").equals("1"), "Row missing in same tx");
            check(db.observe("SELECT count(*) FROM post_record").equals("0"), "Early commit");
            note("saveAndFlush:observer=0");
        }
        @Transactional public void dirtyRollback(boolean queryFlush) {
            Post post = posts.findById(1L).orElseThrow();
            post.title("new");
            check(em.getFlushMode() == FlushModeType.AUTO, "Expected AUTO");
            check(db.same("SELECT title FROM post_record WHERE id=1").equals("old") && post.version() == 0, "Premature update");
            note("before:same=old,version=0");
            if (queryFlush) {
                long count = em.createQuery("select count(p) from Post p where p.title = :title", Long.class)
                        .setParameter("title", "new").getSingleResult();
                check(count == 1, "Query must see own update");
                note("JPQL:count=1");
            } else { em.flush(); }
            check(db.same("SELECT title FROM post_record WHERE id=1").equals("new") && post.version() == 1, "Update/version not flushed");
            check(db.row().equals("old:0"), "Dirty update visible before commit");
            note("after:same=new,version=1,observer=old:0");
            throw new RollbackProbe();
        }
        @Transactional public void uniqueAtFlush() {
            Post post = posts.findById(1L).orElseThrow();
            post.slug("second");
            note("beforeFlush");
            em.flush();
            note("afterFlush");
        }
        @Transactional public void deferredAtCommit() {
            Post post = posts.findById(1L).orElseThrow();
            post.title("new");
            em.flush();
            db.jdbc.update("INSERT INTO outbox_record(id,post_id) VALUES (1,999)");
            em.flush();
            check(db.same("SELECT count(*) FROM outbox_record").equals("1"), "Deferred row missing");
            check(db.observe("SELECT count(*) FROM outbox_record").equals("0") && db.row().equals("old:0"), "Early visibility");
            note("flushSucceeded;bodyReturning");
        }
    }
    static String sqlState(Throwable error) {
        Set<Throwable> seen = Collections.newSetFromMap(new IdentityHashMap<>());
        for (Throwable current = error; current != null && seen.add(current); current = current.getCause())
            if (current instanceof SQLException sql) return sql.getSQLState();
        return "none";
    }
    static void run(String name, boolean seed, Runnable action, Class<? extends Throwable> expected,
                    String state, List<String> steps, String finalRow, String finalCount, Db db, Trace trace) {
        db.reset(seed); trace.steps.clear();
        Throwable failure = null;
        try { action.run(); } catch (RuntimeException e) { failure = e; }
        check(expected == null ? failure == null : expected.isInstance(failure), "Unexpected failure " + name + ": " + failure);
        check(sqlState(failure).equals(state), "Unexpected SQLSTATE " + name);
        check(trace.steps.equals(steps), "Unexpected milestones " + name + ": " + trace.steps);
        check(!TransactionSynchronizationManager.isActualTransactionActive(), "Leaked transaction");
        check(db.observe("SELECT count(*) FROM post_record").equals(finalCount), "Final post count " + name);
        check(db.observe("SELECT count(*) FROM outbox_record").equals("0"), "Final outbox count " + name);
        if (finalRow != null) check(db.row().equals(finalRow), "Final title/version " + name);
        if (seed) check(db.observe("SELECT string_agg(slug,',' ORDER BY id) FROM post_record").equals("first,second"), "Slug rollback " + name);
        System.out.printf("PASS %s posts=%s row=%s outbox=0 error=%s sqlState=%s steps=%s%n", name, finalCount,
                finalRow == null ? "absent" : finalRow, failure == null ? "none" : failure.getClass().getSimpleName(), state, trace.steps);
    }
    public static void main(String[] args) throws Exception {
        String mode = args.length == 0 ? "guided" : args[0];
        if (!Set.of("guided", "verify").contains(mode)) throw new IllegalArgumentException("Use guided or verify");
        if (mode.equals("guided")) {
            System.out.println("예상: ID를 받으면 커밋됐을까요? flush 후 다른 연결은 새 제목을 볼까요? flush 성공 뒤 커밋이 실패할까요?");
            System.out.println("Enter: 임시 PostgreSQL에서 여섯 실험 실행 / q: 종료");
            if (new Scanner(System.in).nextLine().strip().equalsIgnoreCase("q")) return;
        }
        try (var postgres = EmbeddedPostgres.builder().setServerConfig("listen_addresses", "127.0.0.1")
                .setServerConfig("shared_buffers", "32MB").setPort(0).start();
             var context = new AnnotationConfigApplicationContext()) {
            context.registerBean(DataSource.class, () -> postgres.getPostgresDatabase());
            context.register(Config.class); context.refresh();
            var db = context.getBean(Db.class); var service = context.getBean(Service.class); var trace = context.getBean(Trace.class);
            db.init();
            try (var connection = db.ds.getConnection()) {
                System.out.printf("Spring=%s Hibernate=%s SpringDataJPA=%s PostgreSQL=%s JDBC=%s%n", SpringVersion.getVersion(),
                        Version.getVersionString(), PostRepository.class.getInterfaces()[0].getPackage().getImplementationVersion(),
                        connection.getMetaData().getDatabaseProductVersion(), connection.getMetaData().getDriverVersion());
            }
            run("identity-rollback", false, service::identityRollback, RollbackProbe.class, "none",
                    List.of("save:same=1,observer=0,idAssigned=true", "flush:observer=0"), null, "0", db, trace);
            run("saveAndFlush-commit", false, service::flushThenCommit, null, "none",
                    List.of("saveAndFlush:observer=0"), "new:0", "1", db, trace);
            run("dirty-flush-rollback", true, () -> service.dirtyRollback(false), RollbackProbe.class, "none",
                    List.of("before:same=old,version=0", "after:same=new,version=1,observer=old:0"), "old:0", "2", db, trace);
            run("auto-query-rollback", true, () -> service.dirtyRollback(true), RollbackProbe.class, "none",
                    List.of("before:same=old,version=0", "JPQL:count=1", "after:same=new,version=1,observer=old:0"), "old:0", "2", db, trace);
            run("unique-at-flush", true, service::uniqueAtFlush, RuntimeException.class, "23505",
                    List.of("beforeFlush"), "old:0", "2", db, trace);
            run("deferred-at-commit", true, service::deferredAtCommit, RuntimeException.class, "23503",
                    List.of("flushSucceeded;bodyReturning"), "old:0", "2", db, trace);
            System.out.println("ALL 6 SCENARIOS PASSED. 비교 해설: spring/02-jpa-flush-commit/ANSWERS.md");
        }
    }
}
